TERMINOS DE USO DE CALIBURNUS CORDOVA STORE 
=============

La presente declarara los términos de uso de la plataforma Cordova Store para todo tipo de usuario (Final, Beta Tester). 
Le rogamos que los lea atentamente. Son de aplicación al software antes mencionado, el Cual incluye los soportes físicos en los que lo haya recibido, si los hubiera. Los términos de la licencia en papel impreso que se puedan incluir con el software ocupan el lugar de Cualquier término de licencia en pantalla. Si obtiene actualizaciones o complementos directamente de CALIBURNUS, es CALIBURNUS y no el fabricante ni el instalador, quien le otorga las licencias. Al hacer uso del software, usted estará aceptando estos términos. Los Diseños “Windows Modern UI”, son solo una Inspiración de Microsoft ® Windows ® 8.

BETA TESTER
=============

- 1. CÓDIGO. AQUELLOS USUARIOS QUE SE PRESTEN PARA DESARROLLAR PRUEBAS EN BASE AL CÓDIGO O PROGRAMA QUE CALIBURNUS ESTE BRINDANDO BAJO CONSENTIMIENTO, ES OBLIGATORIO QUE BRINDE DETALLES EXACTOS DE PROBLEMAS O CORRECCIONES QUE SE VEAN POSIBLES / OBLIGADAS O ALTERNATIVAS A MODIFICACIONES EN EL CÓDIGO. 
- 2. NOTIFICACIÓN DE ERRORES. LOS BETA TESTER PODRÁN DECLARAR ERRORES EN EL SERVICIO (ORTOGRÁFICOS, ENLACES CAÍDOS, ERRORES DE APLICACIÓN O DE SERVIDOR) DESDE EL FORMULARIO OFICIAL. 


USUARIOS FINAL
=============

- 1. COMPROMISO DEL DESARROLLADOR. LOS DESARROLLADORES DE LOS PROGRAMAS PUBLICADOS EN EL MERCADO DE APLICACIONES, SON 
LOS ENCARGADOS DE GENERAR LAS ACTUALIZACIONES INDEPENDIENTEMENTE DEL MISMO MERCADO. 
- 2. SEGURIDAD. LOS PROGRAMAS PUBLICADOS EN EL MERCADO DE APLICACIONES ESTAN ANALIZADOS POR 4 
(CUATRO) ANTIVIRUS TOTALMENTE DIFERENTES UNO DEL OTRO, ASEGURANDO QUE EL USUARIO ESTA BAJANDO UN PROGRAMA SEGURO Y LIBRE DE VIRUS. 
- 3. QUEJAS. EL USUARIO DISPONE DEL CONTACTO LIBRE ANTE UNA QUEJA O CONSULTA PARA CON EL SERVICIO. 

4. NOTIFICACIÓN DE ERRORES. LOS BETA TESTER PODRÁN DECLARAR ERRORES EN EL SERVICIO (ORTOGRAFICOS, ENLACES CAIDOS, ERRORES DE APLICACIÓN O DE SERVIDOR) DESDE EL FORMULARIO OFICIAL. 
CALIBURNUS Y COMPROMISO 
	A.	CALIBURNUS, ES EL DESARROLLADOR ENTERAMENTE DE CORDOVA STORE. EL MISMO, ES EDITADO – ACTUALIZADO Y MANTENIDO POR LA MISMA CALIBURNUS.  
	B.	TODAS LAS ACTUALIZACIONES CORRESPONDIENTES AL CLIENTE DE LA PLATAFORMA, CORRESPONDEN A CALIBURNUS.  
	C.	CALIBURNUS NO SE HACE RESPONSABLE DE DAÑOS GENERADOS EN EL EQUIPO, DADO A QUE EL SOFTWARE ACLARA AL USUARIO LAS “DEPENDENCIAS” NECESARIAS PARA SU USO.  
	D.	CADA UNO DE LOS PROGRAMAS DECLARADOS EN EL MERCADO, CORRESPONDE A UN EDITOR, EL CUAL ES EL ENCARGADO DE LA MISMA APLICACIÓN Y ESTÁ SUJETA A TÉRMINOS DE USO O LICENCIAS EXPLICITAS EN LA INSTALACIÓN DE CADA APLICACIÓN.  
	E.	EL SERVICIO ESTÁ TOTALMENTE INDEPENDIENTE A CADA EDITOR/DESARROLLADOR DE CADA APLICACIÓN.  
	F.	EL SERVICIO PUEDE SUFRIR ACTUALIZACIONES INESPERADAS PARA EL USUARIO CON MOTIVO DE “INNOVACION”.  
*COMPROMISO*: EL COMPROMISO DE CALIBURNUS PARA CON EL USUARIO ES DE GENERAR UN MERCADO DE APLICACIONES TOTALMENTE GRATUITAS Y SEGURAS. 
